config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:update, :destroy] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"].freeze
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit]
  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/:id
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # GET /restaurants/:id/edit
  def edit
  end

  # PATCH /restaurants/:id
  # def update
  #   @restaurant.update(restaurant_params)
  #   redirect_to restaurants_path
  # end

  # DELETE /restaurants/:id
  # def destroy
  #   @restaurant.destroy
  #   # no need for app/views/restaurants/destroy.html.erb
  #   redirect_to restaurants_path
  # end

private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else

      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<br>
<div class="container">
  <div class="row">

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

    <div class="col-sm-4">
      <h1>New Restaurant</h1>

        <%= simple_form_for(@restaurant) do |f| %>

          <%= f.input :name %>
          <%= f.input :category, collection: Restaurant::CATEGORIES %>
          <%= f.input :address %>
          <%= f.input :phone_number %>

          <div style="text-align: center">
          <%= f.submit class: 'btn btn-primary' %>
          </div>
        <% end %>
      <br>
      <div style="text-align: center">
      <%= link_to "Back to the list of all restaurants" , restaurants_path, class: 'btn btn-primary' %>
      </div>
    </div>

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

  </div>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

    <div class="col-sm-4">
      <div style="margin-left: 20px">
        <h1>All restaurants:</h1>
        <ul>
          <% @restaurants.each do |restaurant| %>
            <li><%= link_to restaurant.name , restaurant_path(restaurant.id) %></li>
          <% end %>
        </ul>
        <div style="text-align: center">
        <%= link_to "Create new restaurant" , new_restaurant_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

    <div class="col-sm-4">
      <div style="margin-left: 20px">
        <h1><%= @restaurant.name %></h1>

        <ul>
          <li><%= @restaurant.category %></li>
          <li><%= @restaurant.address %></li>
          <li><%= @restaurant.phone_number %></li>
        </ul>

        <div style="text-align: center">
          <%= link_to "See all reviews" , restaurant_reviews_path(@restaurant), class: 'btn btn-primary' %>
        </div>
        <br>

        <div style="text-align: center">
          <%= link_to "Edit restaurant" , edit_restaurant_path, class: 'btn btn-primary' %>
        </div>
        <br>

        <div style="text-align: center">
          <%= link_to "Back to the list of all restaurants" , restaurants_path, class: 'btn btn-primary' %>
        </div>

      </div>
    </div>

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

  </div>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

    <div class="col-sm-4">
      <div style="margin-left: 20px">
        <h1><% @restaurant.name %> reviews:</h1>
        <ul>
          <% @restaurant.reviews.each do |review| %>
            <li><%=  review.content %></li>
            <li><%= review.rating %></li>
          <% end %>
        </ul>
        <div style="text-align: center">
        <%= link_to "Add a review" , new_restaurant_review_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

  </div>
</div>

app/views/reviews/new.html.erb
<br>
<div class="container">
  <div class="row">

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

    <div class="col-sm-4">
      <h1>New Review</h1>

        <%= simple_form_for [@restaurant, @review] do |f| %>

          <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5]%>
          <%= f.input :content %>

          <div style="text-align: center">
          <%= f.submit class: 'btn btn-primary' %>
          </div>
        <% end %>
      <br>
      <div style="text-align: center">
        <%= link_to "Back to restaurant" , restaurant_path(@restaurant), class: 'btn btn-primary' %>
      </div>
      <br>
      <div style="text-align: center">
        <%= link_to "Back to the list of all restaurants" , restaurants_path, class: 'btn btn-primary' %>
      </div>
    </div>

    <div class="col-sm-4">
      <!-- One of three columns -->
    </div>

  </div>
</div>